import "./globals.css";
import localFont from 'next/font/local'
import Nav from "@/components/Nav";

const raleway = localFont({ src: './fonts/Raleway-Medium.ttf', variable: "--raleway" })
const forte = localFont({ src: './fonts/forte.ttf', variable: "--forte" })
const rony = localFont({ src: './fonts/Ronysiswadi.ttf', variable: "--rony" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${forte.variable} ${rony.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
